In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_percentage_error

In [2]:
houses= pd.read_csv('../datasets/Housing.csv')
houses.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [3]:
X_train= houses.loc[:, 'area': 'stories'].to_numpy()
Y_train= houses['price'].to_numpy().reshape(-1, 1)

In [4]:
scaler= StandardScaler()
X_norm= scaler.fit_transform(X_train)
Y_norm= scaler.fit_transform(Y_train)
print(f'Range in original data: {np.ptp(X_train, axis= 0)}')
print(f'Range in normalized data: {np.ptp(X_norm, axis=0)}')

Range in original data: [14550     5     3     3]
Range in normalized data: [6.71079293 6.78070523 5.97599535 3.46142038]


In [ ]:
model= LinearRegression()
model.fit(X_norm, Y_norm)
W= model.coef_
b= model.intercept_
print(f'W={W}\nb={b}')

W=[[0.44091592 0.07824617 0.32241309 0.24654881]]
b=[3.32413426e-16]


In [6]:
y_pred_norm= model.predict(X_norm)
y_pred_norm[0:5]

array([[1.36953894],
       [3.25167658],
       [1.4954921 ],
       [1.10133809],
       [0.44282286]])

In [7]:
y_norm_calc= X_norm@ W.reshape(-1,1) + b
y_norm_calc[0:5]

array([[1.36953894],
       [3.25167658],
       [1.4954921 ],
       [1.10133809],
       [0.44282286]])

In [8]:
y_pred_norm[-4:]

array([[-0.96862944],
       [-0.82664246],
       [-0.86491558],
       [-0.389287  ]])

In [9]:
error= mean_absolute_percentage_error(Y_norm, y_pred_norm)
print(error)

5.411211089343711
